eureka: 
  instance: 
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}
spring:
  cloud:
    config:
      allowOverride: true
      overrideNone: false
      overrideSystemProperties: true